spark.hadoop.fs.defaultFS hdfs://namenode:8020
spark.hadoop.hive.metastore.uris thrift://hive-metastore:9083
spark.sql.catalogImplementation hive
spark.sql.warehouse.dir hdfs://namenode:8020/warehouse
spark.jars.ivy /tmp/.ivy2
spark.jars.packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
spark.pyspark.python /opt/bitnami/python/bin/python
spark.pyspark.driver.python /opt/bitnami/python/bin/python
